spring:
  profiles:
    active: sandbox
    
---
spring:
  profiles: sandbox
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shaikapsar/osc
server:
  port: 8888
  
logging:
  level:
    org.hibernate: ERROR
    org.springframeworK: DEBUG
    
  file: config.log
  path: .

---
spring:
  profiles: cloud
  cloud:
    config:
      server:
        git:
         uri: https://github.com/shaikapsar/osc
          
server:
  port: 8888
---
spring:
  profiles: docker
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shaikapsar/osc
          
server:
  port: 8888